# ISDS 7075 Summer 2026 - Group 4 Project

## Chronic Kidney Disease Analysis

### Group Members: Thais Diaz, Cody Tatom, Rhonda Swider

## Wrangling of Data

In [150]:
#Import required packages

import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns

#Figures inline and set visualization style
%matplotlib inline
sns.set()

### Import the data

In [151]:
df_kd = pd.read_excel("../data/ML_project_kidney_disease.xlsx")
df_kd_fields = pd.read_excel("../data/ML_project_kidney_disease.xlsx", sheet_name = "Fields")

In [152]:
df_kd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
 26  CKD_class       400 non-null    int64
dtypes: float64(11), int64(2), object(14)
memory usage: 84.5+ KB

### Identify Missing Values
Total number of rows is 400. 
Missing values in almost all fields.

In [153]:
df_kd.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,wc,rc,htn,dm,cad,appet,pe,ane,classification,CKD_class
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,7800,5.2,yes,yes,no,good,no,no,ckd,1
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,6000,NaN,no,no,no,good,no,no,ckd,1
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,7500,NaN,no,yes,no,poor,no,yes,ckd,1
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,6700,3.9,yes,no,no,poor,yes,yes,ckd,1
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,7300,4.6,no,no,no,good,no,no,ckd,1

### Investigate Data Structure/dictionary

In [154]:
#Investigate data structure/dictionary from reference info on website
#This pulls in from second sheettab appended in Excel data file
df_kd_fields

,Name,Description,Type,value_info
0,age,age,Integer,age in years
1,bp,blood pressure,Integer,bp in mm/Hg
2,sg,specific gravity,Categorical,"1.005,1.010,1.015,1.020,1.025"
3,al,albumin,Categorical,"0,1,2,3,4,5"
4,su,sugar,Categorical,"0,1,2,3,4,5"
5,rbc,red blood cells,Binary,"normal,abnormal"
6,pc,pus cell,Binary,"normal,abnormal"
7,pcc,pus cell clumps,Binary,"present,notpresent"
8,ba,bacteria,Binary,"present,notpresent"
9,bgr,blood gluucose random,Integer,bgr in mgs/dl
10,bu,blood urea,Integer,bu in mgs/dl
11,sc,serum creatinine,Continuous,sc in mgs/dl
12,sod,sodium,Integer,sod in mEq/L
13,pot,potassium,Continuous,pot in mEq/L
14,hemo,hemoglobin,Continuous,hemo in gms
15,pcv,packed cell volume,Integer,numerical
16,wc,white blood cell count,Integer,wc in cells/cumm
17,rc,red blood cell count,Continuous,rc in millions/cmm
18,htn,hypertension,Binary,htn - (yes/no)
19,dm,diabetes mellitus,Binary,dm - (yes/no)
20,cad,coronary artery disease,Binary,cad - (yes/no)
21,appet,appetite,Binary,"appet - (good,poor)"
22,pe,pedal edema,Binary,"pe - (yes,no)"
23,ane,anemia,Binary,"ane - (yes,no)"
24,class,class,Binary,"class - (ckd,notckd)"
25,CKD_class,chronic kidney disease class,Binary,"class - (1,0)"

### Adjust for Missing values

In [155]:
#age is missing 9 values - Replace with avg age - recast as Int
#Compute avg_age
avg_age = df_kd['age'].mean(axis=0)
print("Average age: ", avg_age)
#Replace "NaN" by mean value in 'age' column
df_kd['age'].replace(np.nan, avg_age, inplace = True) 
df_kd['age'] = df_kd['age'].astype(int)

Average age:  51.48337595907928

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\3199127390.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['age'].replace(np.nan, avg_age, inplace = True)

In [156]:
#bp is missing 12 values - Replace with avg bp - recast as Int
#Compute avg_bp
avg_bp = df_kd['bp'].mean(axis=0)
print("Average bp: ", avg_bp)
#Replace "NaN" by mean value in 'bp' column
df_kd['bp'].replace(np.nan, avg_bp, inplace = True) 
df_kd['bp'] = df_kd['bp'].astype(int)

Average bp:  76.46907216494846

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\3082993240.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['bp'].replace(np.nan, avg_bp, inplace = True)

In [157]:
#sg is missing 47 values
df_kd['sg'].value_counts()

sg
1.020    106
1.010     84
1.025     81
1.015     75
1.005      7
Name: count, dtype: int64

In [158]:
#al is missing 46 values
df_kd['al'].value_counts()

al
0.0    199
1.0     44
2.0     43
3.0     43
4.0     24
5.0      1
Name: count, dtype: int64

In [159]:
#su is missing 49 values
df_kd['su'].value_counts()

su
0.0    290
2.0     18
3.0     14
4.0     13
1.0     13
5.0      3
Name: count, dtype: int64

In [160]:
#rbc is missing 52 values
df_kd['rbc'].value_counts()

rbc
normal      201
abnormal     47
Name: count, dtype: int64

In [161]:
#pc is missing 65 values
df_kd['pc'].value_counts()

pc
normal      259
abnormal     76
Name: count, dtype: int64

In [162]:
#pcc is missing 4 values
df_kd['pcc'].value_counts()
#replace missing values of 'pcc' with 'notpresent'
df_kd['pcc'].replace(np.nan,'notpresent', inplace=True)

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\3059995983.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['pcc'].replace(np.nan,'notpresent', inplace=True)

In [163]:
#ba is missing 4 values
df_kd['ba'].value_counts()
#replace missing values of 'ba' with 'notpresent'
df_kd['ba'].replace(np.nan,'notpresent', inplace=True)

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\1426584899.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['ba'].replace(np.nan,'notpresent', inplace=True)

In [164]:
#bgr is missing 44 values - Replace with avg bgr - recast as Int
#Compute avg_bgr
avg_bgr = df_kd['bgr'].mean(axis=0)
print("Average bgr: ", avg_bgr)
#Replace "NaN" by mean value in 'bgr' column
df_kd['bgr'].replace(np.nan, avg_bgr, inplace = True) 
df_kd['bgr'] = df_kd['bgr'].astype(int)

Average bgr:  148.0365168539326

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\1761785724.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['bgr'].replace(np.nan, avg_bgr, inplace = True)

In [165]:
#bu is missing 19 values - Replace with avg buu - recast as Int
#Compute avg_bu
avg_bu = df_kd['bu'].mean(axis=0)
print("Average bu: ", avg_bu)
#Replace "NaN" by mean value in 'bu' column
df_kd['bu'].replace(np.nan, avg_bu, inplace = True) 
df_kd['bu'] = df_kd['bu'].astype(int)

Average bu:  57.425721784776904

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\2979069225.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['bu'].replace(np.nan, avg_bu, inplace = True)

In [166]:
#sc missing 17 values - Replace with avg sc - recast as float

#Compute avg_sc
avg_sc = df_kd['sc'].mean(axis=0)
print("Average sc: ", avg_sc)
#Replace "NaN" by mean value in 'sc' column
df_kd['sc'].replace(np.nan, avg_sc, inplace = True) 
df_kd['sc'] = df_kd['sc'].astype(int)

Average sc:  3.072454308093995

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\1339582682.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['sc'].replace(np.nan, avg_sc, inplace = True)

In [167]:
#sod missing 87 values  -- Too many values missing?

In [168]:
#pot missing 88 values  -- Too many values missing?

In [169]:
#hemo missing 52 values  -- Too many values missing?

In [170]:
#pcv missing 70 values  -- Too many values missing?

In [171]:
#wc missing 105 values  -- Too many values missing?

In [172]:
#rc missing 130 values  -- Too many values missing?

In [173]:
#htn missing 2 values
df_kd['htn'].value_counts()
#Replace with max count value
df_kd['htn'].replace(np.nan,'no',inplace=True)

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\2706430390.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['htn'].replace(np.nan,'no',inplace=True)

In [174]:
#dm missing 2 values
df_kd['dm'].value_counts()
#Replace with max count value
df_kd['dm'].replace(' yes','yes', inplace=True)
df_kd['dm'].replace('\tyes','yes',inplace=True)
df_kd['dm'].replace('\tno','no',inplace=True)

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\868839027.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['dm'].replace(' yes','yes', inplace=True)
C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\868839027.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['dm'].replace('\tyes','yes',inplace=True)
C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\868839027.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['dm'].replace('\tno','no',inplace=True)

In [175]:
#cad missing 2 values 
df_kd['cad'].value_counts()
#Replace with max count value
df_kd['cad'].replace(np.nan,'no',inplace=True)

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\2283293214.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['cad'].replace(np.nan,'no',inplace=True)

In [176]:
#appet missing 1 value
df_kd['appet'].value_counts()
#Replace with max count value
df_kd['appet'].replace(np.nan,'good',inplace=True)

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\668089827.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['appet'].replace(np.nan,'good',inplace=True)

In [177]:
#pe missing 1 value
df_kd['pe'].value_counts()
#Replace with max count value
df_kd['pe'].replace(np.nan,'no',inplace=True)

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\389680503.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['pe'].replace(np.nan,'no',inplace=True)

In [178]:
#ane missing 1 value
df_kd['ane'].value_counts()
#Replace with max count value
df_kd['ane'].replace(np.nan,'no', inplace=True)

C:\Users\RhondaSwider\AppData\Local\Temp\ipykernel_42380\1661931810.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_kd['ane'].replace(np.nan,'no', inplace=True)